project:
  type: website
  resources:
    - CV_Leonardo2025.pdf

website:
  title: ""
  favicon: images/Brain_icon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: 
    left: "©2025, Leonardo Pinto Arata ∙ Made with ☀️️ and Quarto ∙ Memento Mori" 
  navbar:
    title: Leonardo Pinto Arata
    left:
      - href: publications.qmd  
        text: Publications
        icon: mortarboard
      - href: Research.qmd
        text: Research
      - href: News.qmd  
        text: News
      - href: CV_Leonardo2025.pdf  
        text: CV
        target: _blank
        rel: noopener
      
format: 
  html:
    theme: [minty, styles.scss]

